### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by shihofuyu** [tiaanv/SBKA#6]
Hi, I can't seem to get this tool to work on Windows 11 with Harman Soundstick speakers. Even when I set the PC volume to 100, the output doesn't seem to be enough to wake up the speakers/keep them from going to sleep, pictured below. Is it supposed to be this low and/or is there anything I can do about it? Is there something else I'm doing wrong? To get it running it's just dragging the 2 files from the zip on my PC and start the exe right? As far as general audio in the PC goes I haven't changed anything.
![2023-12-31 062211](https://github.com/tiaanv/SBKA/assets/46304324/5c2f5325-c027-40cc-a4c4-61560cb8ae32)

**Comment by tiaanv** [comment]
The output level has by design, been normalised to a fairly low output volume.  This should be enough for any speaker that is analysing the the input waveform.

My first question is: Do you hear a sound when you use the test button?  I specifically designed the TEST button frequency to be in the audible range for testing.

If you can't hear it, something is not set up correctly.  Perhaps the incorrect output device.

If you can hear it, then your speakers suck ;) And is either using a low-cut filter to ignore the low-frequency output generated, or it's not sensitive enough for low-volume output....  Both of which are not great.

Let me know, and we can decide what to do further.

T

**Comment by shihofuyu** [comment]
Thanks for the quick reply. I do hear the test sound and the output device is set correctly.

**Comment by tiaanv** [comment]
OK.
Can you confirm that the Last sound played, is updating from time to time, to confirm that the app is doing its thing in the background?

If so, then the only other option I can think of is to add a new config to "boost" the output volume.  Then we can see if that adresses the issue.

T

**Comment by shihofuyu** [comment]
Yes, it updates everytime a sound is played from the tool and the detection updates everytime a sound is played from the PC too.

**Comment by tiaanv** [comment]
https://github.com/tiaanv/SBKA/releases/tag/V1.5.0

Try this release, and change the Boost level to see if that solves the issue.  If it does not, it could also be that the low-frequency output does not satisfy the speakers' requirement for sound detection.

Let me know how it goes.

**Comment by shihofuyu** [comment]
This did the trick! Thank you so much
